# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(735, 535)
        Dialog.setMaximumSize(QtCore.QSize(735, 535))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:rgb(71, 145, 255)")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 480, 161, 32))
        self.buttonBox.setMaximumSize(QtCore.QSize(535, 735))
        self.buttonBox.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 60, 716, 400))
        self.frame.setMinimumSize(QtCore.QSize(0, 400))
        self.frame.setStyleSheet("background:white;\n"
"border-radius:33px\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(9, 0, 9, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.s_quantity = QtWidgets.QSpinBox(self.frame)
        self.s_quantity.setMinimumSize(QtCore.QSize(0, 50))
        self.s_quantity.setWhatsThis("")
        self.s_quantity.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_quantity.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.s_quantity.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.s_quantity.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.s_quantity.setMaximum(999999999)
        self.s_quantity.setDisplayIntegerBase(10)
        self.s_quantity.setObjectName("s_quantity")
        self.horizontalLayout_3.addWidget(self.s_quantity)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(150, 50))
        self.label_4.setStyleSheet("font: 75 12pt \"Amiri\";\n"
"margin-right: 35px")
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("font: 75 11pt \"Amiri\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s_proName = QtWidgets.QLineEdit(self.frame)
        self.s_proName.setMinimumSize(QtCore.QSize(50, 50))
        self.s_proName.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.s_proName.setObjectName("s_proName")
        self.horizontalLayout.addWidget(self.s_proName)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setStyleSheet("font: 75 12pt \"Amiri\";\n"
"margin-right: 35px")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.s_barcode = QtWidgets.QLineEdit(self.frame)
        self.s_barcode.setMinimumSize(QtCore.QSize(50, 50))
        self.s_barcode.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.s_barcode.setReadOnly(False)
        self.s_barcode.setObjectName("s_barcode")
        self.horizontalLayout.addWidget(self.s_barcode)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(150, 50))
        self.label.setStyleSheet("font: 75 12pt \"Amiri\";\n"
"margin-right: 35px")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.s_price_2 = QtWidgets.QSpinBox(self.frame)
        self.s_price_2.setMinimumSize(QtCore.QSize(100, 50))
        self.s_price_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_price_2.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.s_price_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.s_price_2.setMaximum(999999999)
        self.s_price_2.setSingleStep(99)
        self.s_price_2.setDisplayIntegerBase(10)
        self.s_price_2.setObjectName("s_price_2")
        self.horizontalLayout_2.addWidget(self.s_price_2)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMinimumSize(QtCore.QSize(50, 50))
        self.label_6.setStyleSheet("font: 75 12pt \"Amiri\";\n"
"margin-right: 35px")
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.s_price = QtWidgets.QSpinBox(self.frame)
        self.s_price.setMinimumSize(QtCore.QSize(100, 50))
        self.s_price.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_price.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.s_price.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.s_price.setMaximum(999999999)
        self.s_price.setObjectName("s_price")
        self.horizontalLayout_2.addWidget(self.s_price)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.label_3.setStyleSheet("font: 75 12pt \"Amiri\";\n"
"margin-right: 35px")
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setStyleSheet("font: 75 11pt \"Amiri\";")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add product"))
        self.label_4.setText(_translate("Dialog", "الكمية"))
        self.label_5.setText(_translate("Dialog", "تاريخ انتهاء الصلاحية"))
        self.s_proName.setPlaceholderText(_translate("Dialog", "ادخل اسم المنتج"))
        self.label_2.setText(_translate("Dialog", "اسم المنتج"))
        self.s_barcode.setPlaceholderText(_translate("Dialog", "ادخل الكود بار"))
        self.label.setText(_translate("Dialog", "كود بار"))
        self.label_6.setText(_translate("Dialog", "مبلغ الشراء"))
        self.label_3.setText(_translate("Dialog", "مبلغ البيع"))
        self.checkBox.setText(_translate("Dialog", "ﻻ يحتوي على كود بار"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
