# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user_debt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(616, 254)
        Dialog.setMaximumSize(QtCore.QSize(616, 254))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setStyleSheet("background:white")
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.d_userName = QtWidgets.QLineEdit(Dialog)
        self.d_userName.setMinimumSize(QtCore.QSize(400, 50))
        self.d_userName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.d_userName.setAutoFillBackground(False)
        self.d_userName.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.d_userName.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        self.d_userName.setPlaceholderText("")
        self.d_userName.setClearButtonEnabled(True)
        self.d_userName.setObjectName("d_userName")
        self.horizontalLayout.addWidget(self.d_userName)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(190, 0))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.d_phoneNum = QtWidgets.QSpinBox(Dialog)
        self.d_phoneNum.setMinimumSize(QtCore.QSize(400, 50))
        self.d_phoneNum.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.d_phoneNum.setWrapping(False)
        self.d_phoneNum.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.d_phoneNum.setMaximum(999999999)
        self.d_phoneNum.setDisplayIntegerBase(10)
        self.d_phoneNum.setObjectName("d_phoneNum")
        self.horizontalLayout_2.addWidget(self.d_phoneNum)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(150, 50))
        self.buttonBox.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add user"))
        self.label_2.setText(_translate("Dialog", "الاسم "))
        self.label.setText(_translate("Dialog", "رقم الهاتف"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
