# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontEnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1202, 624)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.d_tableContent = QtWidgets.QTableWidget(self.page_4)
        self.d_tableContent.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.d_tableContent.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.d_tableContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.d_tableContent.setObjectName("d_tableContent")
        self.d_tableContent.setColumnCount(4)
        self.d_tableContent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent.setHorizontalHeaderItem(3, item)
        self.d_tableContent.horizontalHeader().setDefaultSectionSize(200)
        self.d_tableContent.horizontalHeader().setSortIndicatorShown(True)
        self.d_tableContent.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.d_tableContent, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.d_search_input = QtWidgets.QLineEdit(self.page_4)
        self.d_search_input.setMinimumSize(QtCore.QSize(300, 50))
        self.d_search_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.d_search_input.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.d_search_input.setClearButtonEnabled(True)
        self.d_search_input.setObjectName("d_search_input")
        self.horizontalLayout_5.addWidget(self.d_search_input)
        self.d_searchbtn = QtWidgets.QPushButton(self.page_4)
        self.d_searchbtn.setMinimumSize(QtCore.QSize(77, 50))
        self.d_searchbtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.d_searchbtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.d_searchbtn.setStyleSheet("QPushButton{\n"
"background:rgb(255, 170, 255);\n"
"\n"
"border-style: outset;\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"font: 12pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: silver\n"
"}")
        self.d_searchbtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.d_searchbtn.setIcon(icon1)
        self.d_searchbtn.setIconSize(QtCore.QSize(32, 32))
        self.d_searchbtn.setObjectName("d_searchbtn")
        self.horizontalLayout_5.addWidget(self.d_searchbtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.d_showBook = QtWidgets.QPushButton(self.page_4)
        self.d_showBook.setMinimumSize(QtCore.QSize(0, 50))
        self.d_showBook.setMaximumSize(QtCore.QSize(16777215, 50))
        self.d_showBook.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.d_showBook.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.d_showBook.setIcon(icon2)
        self.d_showBook.setIconSize(QtCore.QSize(32, 32))
        self.d_showBook.setObjectName("d_showBook")
        self.horizontalLayout_5.addWidget(self.d_showBook)
        self.d_deleteUser = QtWidgets.QPushButton(self.page_4)
        self.d_deleteUser.setMinimumSize(QtCore.QSize(0, 50))
        self.d_deleteUser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.d_deleteUser.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.d_deleteUser.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/remove-friend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.d_deleteUser.setIcon(icon3)
        self.d_deleteUser.setIconSize(QtCore.QSize(32, 32))
        self.d_deleteUser.setObjectName("d_deleteUser")
        self.horizontalLayout_5.addWidget(self.d_deleteUser)
        self.d_addUser = QtWidgets.QPushButton(self.page_4)
        self.d_addUser.setMinimumSize(QtCore.QSize(0, 50))
        self.d_addUser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.d_addUser.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.d_addUser.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/follow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.d_addUser.setIcon(icon4)
        self.d_addUser.setIconSize(QtCore.QSize(32, 32))
        self.d_addUser.setObjectName("d_addUser")
        self.horizontalLayout_5.addWidget(self.d_addUser)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.d_total = QtWidgets.QLCDNumber(self.page_4)
        self.d_total.setMinimumSize(QtCore.QSize(500, 50))
        self.d_total.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.d_total.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.d_total.setLineWidth(1)
        self.d_total.setSmallDecimalPoint(True)
        self.d_total.setDigitCount(30)
        self.d_total.setObjectName("d_total")
        self.horizontalLayout_7.addWidget(self.d_total)
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.page_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.s_lcd = QtWidgets.QLCDNumber(self.page_2)
        self.s_lcd.setMinimumSize(QtCore.QSize(700, 50))
        self.s_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.s_lcd.setDigitCount(30)
        self.s_lcd.setObjectName("s_lcd")
        self.horizontalLayout_3.addWidget(self.s_lcd)
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.s_table = QtWidgets.QTableWidget(self.page_2)
        self.s_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_table.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.s_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.s_table.setWordWrap(True)
        self.s_table.setCornerButtonEnabled(False)
        self.s_table.setObjectName("s_table")
        self.s_table.setColumnCount(7)
        self.s_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.s_table.setHorizontalHeaderItem(6, item)
        self.s_table.horizontalHeader().setDefaultSectionSize(200)
        self.s_table.horizontalHeader().setSortIndicatorShown(True)
        self.s_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.s_table, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.s_input = QtWidgets.QLineEdit(self.page_2)
        self.s_input.setMinimumSize(QtCore.QSize(300, 50))
        self.s_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s_input.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.s_input.setClearButtonEnabled(True)
        self.s_input.setObjectName("s_input")
        self.horizontalLayout_2.addWidget(self.s_input)
        self.s_search = QtWidgets.QPushButton(self.page_2)
        self.s_search.setMinimumSize(QtCore.QSize(77, 50))
        self.s_search.setMaximumSize(QtCore.QSize(16777215, 50))
        self.s_search.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_search.setStyleSheet("QPushButton{\n"
"background:rgb(255, 170, 255);\n"
"\n"
"border-style: outset;\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"font: 12pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: silver\n"
"}")
        self.s_search.setText("")
        self.s_search.setIcon(icon1)
        self.s_search.setIconSize(QtCore.QSize(32, 32))
        self.s_search.setObjectName("s_search")
        self.horizontalLayout_2.addWidget(self.s_search)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.s_update = QtWidgets.QPushButton(self.page_2)
        self.s_update.setMaximumSize(QtCore.QSize(16777215, 50))
        self.s_update.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_update.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/loan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.s_update.setIcon(icon5)
        self.s_update.setIconSize(QtCore.QSize(32, 32))
        self.s_update.setObjectName("s_update")
        self.horizontalLayout_2.addWidget(self.s_update)
        self.s_delete = QtWidgets.QPushButton(self.page_2)
        self.s_delete.setMinimumSize(QtCore.QSize(0, 50))
        self.s_delete.setMaximumSize(QtCore.QSize(16777215, 50))
        self.s_delete.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_delete.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.s_delete.setIcon(icon6)
        self.s_delete.setIconSize(QtCore.QSize(32, 32))
        self.s_delete.setObjectName("s_delete")
        self.horizontalLayout_2.addWidget(self.s_delete)
        self.s_add = QtWidgets.QPushButton(self.page_2)
        self.s_add.setMinimumSize(QtCore.QSize(0, 50))
        self.s_add.setMaximumSize(QtCore.QSize(16777215, 50))
        self.s_add.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.s_add.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/add-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.s_add.setIcon(icon7)
        self.s_add.setIconSize(QtCore.QSize(32, 32))
        self.s_add.setObjectName("s_add")
        self.horizontalLayout_2.addWidget(self.s_add)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.u_page_table = QtWidgets.QTableWidget(self.page_5)
        self.u_page_table.setMinimumSize(QtCore.QSize(0, 0))
        self.u_page_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.u_page_table.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.u_page_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.u_page_table.setObjectName("u_page_table")
        self.u_page_table.setColumnCount(3)
        self.u_page_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.u_page_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.u_page_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.u_page_table.setHorizontalHeaderItem(2, item)
        self.u_page_table.horizontalHeader().setDefaultSectionSize(200)
        self.u_page_table.horizontalHeader().setSortIndicatorShown(True)
        self.u_page_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.u_page_table, 4, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.pay = QtWidgets.QPushButton(self.page_5)
        self.pay.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pay.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pay.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/ticket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pay.setIcon(icon8)
        self.pay.setIconSize(QtCore.QSize(32, 32))
        self.pay.setObjectName("pay")
        self.horizontalLayout_10.addWidget(self.pay)
        self.updateInfo = QtWidgets.QPushButton(self.page_5)
        self.updateInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.updateInfo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.updateInfo.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateInfo.setIcon(icon9)
        self.updateInfo.setIconSize(QtCore.QSize(32, 32))
        self.updateInfo.setObjectName("updateInfo")
        self.horizontalLayout_10.addWidget(self.updateInfo)
        self.u_page_delete = QtWidgets.QPushButton(self.page_5)
        self.u_page_delete.setMinimumSize(QtCore.QSize(0, 50))
        self.u_page_delete.setMaximumSize(QtCore.QSize(16777215, 50))
        self.u_page_delete.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.u_page_delete.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.u_page_delete.setIcon(icon6)
        self.u_page_delete.setIconSize(QtCore.QSize(32, 32))
        self.u_page_delete.setObjectName("u_page_delete")
        self.horizontalLayout_10.addWidget(self.u_page_delete)
        self.u_page_show = QtWidgets.QPushButton(self.page_5)
        self.u_page_show.setMinimumSize(QtCore.QSize(0, 50))
        self.u_page_show.setMaximumSize(QtCore.QSize(16777215, 50))
        self.u_page_show.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.u_page_show.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.u_page_show.setIcon(icon5)
        self.u_page_show.setIconSize(QtCore.QSize(32, 32))
        self.u_page_show.setObjectName("u_page_show")
        self.horizontalLayout_10.addWidget(self.u_page_show)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.page_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.u_page_phone = QtWidgets.QLabel(self.page_5)
        self.u_page_phone.setMinimumSize(QtCore.QSize(100, 0))
        self.u_page_phone.setMaximumSize(QtCore.QSize(16777215, 50))
        self.u_page_phone.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.u_page_phone.setStyleSheet("font: 14pt \"Amiri Quran\";")
        self.u_page_phone.setObjectName("u_page_phone")
        self.horizontalLayout_8.addWidget(self.u_page_phone)
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_7.setStyleSheet("font: 14pt \"Amiri Quran\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.u_page_name = QtWidgets.QLabel(self.page_5)
        self.u_page_name.setMinimumSize(QtCore.QSize(100, 0))
        self.u_page_name.setMaximumSize(QtCore.QSize(16777215, 50))
        self.u_page_name.setStyleSheet("font: 14pt \"Amiri Quran\";")
        self.u_page_name.setObjectName("u_page_name")
        self.horizontalLayout_8.addWidget(self.u_page_name)
        self.label_5 = QtWidgets.QLabel(self.page_5)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setStyleSheet("font: 14pt \"Amiri Quran\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.page_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.page_5)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_7.addWidget(self.line_6, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.expired_table = QtWidgets.QTableWidget(self.page_9)
        self.expired_table.setEnabled(True)
        self.expired_table.setMinimumSize(QtCore.QSize(0, 0))
        self.expired_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.expired_table.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.expired_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.expired_table.setObjectName("expired_table")
        self.expired_table.setColumnCount(4)
        self.expired_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.expired_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.expired_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.expired_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.expired_table.setHorizontalHeaderItem(3, item)
        self.expired_table.horizontalHeader().setDefaultSectionSize(200)
        self.expired_table.horizontalHeader().setSortIndicatorShown(True)
        self.expired_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_15.addWidget(self.expired_table, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_9)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.delete_user = QtWidgets.QPushButton(self.page_7)
        self.delete_user.setMinimumSize(QtCore.QSize(0, 50))
        self.delete_user.setMaximumSize(QtCore.QSize(16777215, 50))
        self.delete_user.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_user.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.delete_user.setIcon(icon6)
        self.delete_user.setIconSize(QtCore.QSize(32, 32))
        self.delete_user.setObjectName("delete_user")
        self.horizontalLayout_9.addWidget(self.delete_user)
        self.update_user = QtWidgets.QPushButton(self.page_7)
        self.update_user.setMinimumSize(QtCore.QSize(0, 50))
        self.update_user.setMaximumSize(QtCore.QSize(16777215, 50))
        self.update_user.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.update_user.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.update_user.setIcon(icon9)
        self.update_user.setIconSize(QtCore.QSize(32, 32))
        self.update_user.setObjectName("update_user")
        self.horizontalLayout_9.addWidget(self.update_user)
        self.add_user = QtWidgets.QPushButton(self.page_7)
        self.add_user.setMinimumSize(QtCore.QSize(0, 50))
        self.add_user.setMaximumSize(QtCore.QSize(16777215, 50))
        self.add_user.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.add_user.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.add_user.setIcon(icon4)
        self.add_user.setIconSize(QtCore.QSize(32, 32))
        self.add_user.setObjectName("add_user")
        self.horizontalLayout_9.addWidget(self.add_user)
        self.gridLayout_11.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.table_user = QtWidgets.QTableWidget(self.page_7)
        self.table_user.setMinimumSize(QtCore.QSize(0, 0))
        self.table_user.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.table_user.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.table_user.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_user.setTabKeyNavigation(True)
        self.table_user.setProperty("showDropIndicator", True)
        self.table_user.setObjectName("table_user")
        self.table_user.setColumnCount(4)
        self.table_user.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_user.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_user.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_user.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_user.setHorizontalHeaderItem(3, item)
        self.table_user.horizontalHeader().setDefaultSectionSize(200)
        self.table_user.horizontalHeader().setSortIndicatorShown(True)
        self.table_user.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_11.addWidget(self.table_user, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.bellTable = QtWidgets.QTableWidget(self.page_3)
        self.bellTable.setMinimumSize(QtCore.QSize(0, 0))
        self.bellTable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bellTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.bellTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bellTable.setObjectName("bellTable")
        self.bellTable.setColumnCount(3)
        self.bellTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bellTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bellTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bellTable.setHorizontalHeaderItem(2, item)
        self.bellTable.horizontalHeader().setDefaultSectionSize(300)
        self.bellTable.horizontalHeader().setSortIndicatorShown(True)
        self.bellTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.bellTable, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bell_input = QtWidgets.QLineEdit(self.page_3)
        self.bell_input.setMinimumSize(QtCore.QSize(300, 50))
        self.bell_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bell_input.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.bell_input.setClearButtonEnabled(True)
        self.bell_input.setObjectName("bell_input")
        self.horizontalLayout_6.addWidget(self.bell_input)
        self.searchBell = QtWidgets.QPushButton(self.page_3)
        self.searchBell.setMinimumSize(QtCore.QSize(77, 50))
        self.searchBell.setMaximumSize(QtCore.QSize(16777215, 50))
        self.searchBell.setStyleSheet("QPushButton{\n"
"background:rgb(255, 170, 255);\n"
"\n"
"border-style: outset;\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"font: 12pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: silver\n"
"}")
        self.searchBell.setText("")
        self.searchBell.setIcon(icon1)
        self.searchBell.setIconSize(QtCore.QSize(32, 32))
        self.searchBell.setObjectName("searchBell")
        self.horizontalLayout_6.addWidget(self.searchBell)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.deleteBell = QtWidgets.QPushButton(self.page_3)
        self.deleteBell.setMinimumSize(QtCore.QSize(0, 50))
        self.deleteBell.setMaximumSize(QtCore.QSize(16777215, 50))
        self.deleteBell.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deleteBell.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.deleteBell.setIcon(icon6)
        self.deleteBell.setIconSize(QtCore.QSize(32, 32))
        self.deleteBell.setObjectName("deleteBell")
        self.horizontalLayout_6.addWidget(self.deleteBell)
        self.showBell = QtWidgets.QPushButton(self.page_3)
        self.showBell.setMinimumSize(QtCore.QSize(0, 50))
        self.showBell.setMaximumSize(QtCore.QSize(16777215, 50))
        self.showBell.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showBell.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.showBell.setIcon(icon5)
        self.showBell.setIconSize(QtCore.QSize(32, 32))
        self.showBell.setObjectName("showBell")
        self.horizontalLayout_6.addWidget(self.showBell)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.page_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem10, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.user_settings = QtWidgets.QCommandLinkButton(self.page_8)
        self.user_settings.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.user_settings.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        self.user_settings.setObjectName("user_settings")
        self.verticalLayout_3.addWidget(self.user_settings)
        self.gen_barcode = QtWidgets.QCommandLinkButton(self.page_8)
        self.gen_barcode.setObjectName("gen_barcode")
        self.verticalLayout_3.addWidget(self.gen_barcode)
        self.exDB = QtWidgets.QCommandLinkButton(self.page_8)
        self.exDB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.exDB.setObjectName("exDB")
        self.verticalLayout_3.addWidget(self.exDB)
        self.download = QtWidgets.QCommandLinkButton(self.page_8)
        self.download.setStyleSheet("")
        self.download.setObjectName("download")
        self.verticalLayout_3.addWidget(self.download)
        self.analytic = QtWidgets.QCommandLinkButton(self.page_8)
        self.analytic.setStyleSheet("")
        self.analytic.setObjectName("analytic")
        self.verticalLayout_3.addWidget(self.analytic)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.gridLayout_13.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem13, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget = QtWidgets.QWidget(self.page_6)
        self.widget.setStyleSheet("background:rgb(174, 176, 255)")
        self.widget.setObjectName("widget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("background:white;\n"
"border-radius:25px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.email = QtWidgets.QLineEdit(self.frame_3)
        self.email.setMinimumSize(QtCore.QSize(0, 50))
        self.email.setStyleSheet("background:white")
        self.email.setObjectName("email")
        self.gridLayout_10.addWidget(self.email, 1, 0, 1, 1)
        self.signin = QtWidgets.QPushButton(self.frame_3)
        self.signin.setMinimumSize(QtCore.QSize(0, 50))
        self.signin.setMaximumSize(QtCore.QSize(16777215, 50))
        self.signin.setStyleSheet("background:orange")
        self.signin.setObjectName("signin")
        self.gridLayout_10.addWidget(self.signin, 3, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setMinimumSize(QtCore.QSize(0, 50))
        self.label_8.setStyleSheet("font: 75 italic 14pt \"Amiri\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.gridLayout_10.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.frame_3)
        self.password.setMinimumSize(QtCore.QSize(0, 50))
        self.password.setMaximumSize(QtCore.QSize(16777215, 50))
        self.password.setStyleSheet("background:white")
        self.password.setObjectName("password")
        self.gridLayout_10.addWidget(self.password, 2, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_3, 2, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem16, 2, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem17, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem18, 3, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem19, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_11)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.file_link = QtWidgets.QLabel(self.page_11)
        self.file_link.setMinimumSize(QtCore.QSize(300, 50))
        self.file_link.setMaximumSize(QtCore.QSize(350, 50))
        self.file_link.setStyleSheet("background:white")
        self.file_link.setText("")
        self.file_link.setObjectName("file_link")
        self.horizontalLayout.addWidget(self.file_link)
        self.choose_file = QtWidgets.QPushButton(self.page_11)
        self.choose_file.setMinimumSize(QtCore.QSize(0, 50))
        self.choose_file.setMaximumSize(QtCore.QSize(16777215, 50))
        self.choose_file.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.choose_file.setObjectName("choose_file")
        self.horizontalLayout.addWidget(self.choose_file)
        self.gridLayout_18.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.page_11)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setStyleSheet("background:white;\n"
"border-radius:25px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.excel_tale = QtWidgets.QTableWidget(self.frame_4)
        self.excel_tale.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.excel_tale.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.excel_tale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.excel_tale.setWordWrap(True)
        self.excel_tale.setCornerButtonEnabled(False)
        self.excel_tale.setObjectName("excel_tale")
        self.excel_tale.setColumnCount(7)
        self.excel_tale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(6, item)
        self.excel_tale.horizontalHeader().setDefaultSectionSize(200)
        self.excel_tale.horizontalHeader().setSortIndicatorShown(True)
        self.excel_tale.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_17.addWidget(self.excel_tale, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.gridLayout_18.addLayout(self.verticalLayout_2, 1, 0, 1, 2)
        spacerItem21 = QtWidgets.QSpacerItem(727, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem21, 2, 1, 1, 1)
        self.saveTodb = QtWidgets.QPushButton(self.page_11)
        self.saveTodb.setMaximumSize(QtCore.QSize(16777215, 50))
        self.saveTodb.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.saveTodb.setObjectName("saveTodb")
        self.gridLayout_18.addWidget(self.saveTodb, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.page_12)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.label_12 = QtWidgets.QLabel(self.page_12)
        self.label_12.setMinimumSize(QtCore.QSize(100, 0))
        self.label_12.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.page_12)
        self.label_11.setMinimumSize(QtCore.QSize(100, 0))
        self.label_11.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem23)
        self.today_earns = QtWidgets.QLabel(self.page_12)
        self.today_earns.setMinimumSize(QtCore.QSize(100, 0))
        self.today_earns.setMaximumSize(QtCore.QSize(200, 16777215))
        self.today_earns.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.today_earns.setObjectName("today_earns")
        self.horizontalLayout_12.addWidget(self.today_earns)
        self.label_13 = QtWidgets.QLabel(self.page_12)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem24)
        self.label_10 = QtWidgets.QLabel(self.page_12)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_10.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.page_12)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem25)
        self.gridLayout_19.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_19.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.productsName = QtWidgets.QTableWidget(self.page_12)
        self.productsName.setMinimumSize(QtCore.QSize(0, 0))
        self.productsName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.productsName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.productsName.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.productsName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.productsName.setWordWrap(True)
        self.productsName.setCornerButtonEnabled(False)
        self.productsName.setObjectName("productsName")
        self.productsName.setColumnCount(1)
        self.productsName.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.productsName.setHorizontalHeaderItem(0, item)
        self.productsName.horizontalHeader().setDefaultSectionSize(200)
        self.productsName.horizontalHeader().setSortIndicatorShown(True)
        self.productsName.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_13.addWidget(self.productsName)
        self.gridLayout_19.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_12)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background:white;\n"
"")
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.h_add = QtWidgets.QPushButton(self.frame)
        self.h_add.setMinimumSize(QtCore.QSize(50, 50))
        self.h_add.setMaximumSize(QtCore.QSize(16777215, 50))
        self.h_add.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.h_add.setStyleSheet("QPushButton{\n"
"background:rgb(255, 170, 255);\n"
"\n"
"border-style: outset;\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"font: 12pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: silver\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.h_add.setIcon(icon10)
        self.h_add.setIconSize(QtCore.QSize(32, 32))
        self.h_add.setObjectName("h_add")
        self.gridLayout_8.addWidget(self.h_add, 0, 1, 1, 1)
        self.printBell = QtWidgets.QPushButton(self.frame)
        self.printBell.setMinimumSize(QtCore.QSize(50, 50))
        self.printBell.setMaximumSize(QtCore.QSize(16777215, 50))
        self.printBell.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.printBell.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printBell.setIcon(icon11)
        self.printBell.setIconSize(QtCore.QSize(32, 32))
        self.printBell.setObjectName("printBell")
        self.gridLayout_8.addWidget(self.printBell, 0, 7, 1, 1)
        self.h_input = QtWidgets.QLineEdit(self.frame)
        self.h_input.setMinimumSize(QtCore.QSize(0, 50))
        self.h_input.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.h_input.setText("")
        self.h_input.setObjectName("h_input")
        self.gridLayout_8.addWidget(self.h_input, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem26, 0, 3, 1, 1)
        self.h_delete = QtWidgets.QPushButton(self.frame)
        self.h_delete.setMinimumSize(QtCore.QSize(50, 50))
        self.h_delete.setMaximumSize(QtCore.QSize(16777215, 50))
        self.h_delete.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.h_delete.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"font: 12pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.h_delete.setIcon(icon6)
        self.h_delete.setIconSize(QtCore.QSize(32, 32))
        self.h_delete.setObjectName("h_delete")
        self.gridLayout_8.addWidget(self.h_delete, 0, 2, 1, 1)
        self.addToDebt = QtWidgets.QPushButton(self.frame)
        self.addToDebt.setMinimumSize(QtCore.QSize(50, 50))
        self.addToDebt.setMaximumSize(QtCore.QSize(16777215, 50))
        self.addToDebt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addToDebt.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        self.addToDebt.setIcon(icon7)
        self.addToDebt.setIconSize(QtCore.QSize(32, 32))
        self.addToDebt.setObjectName("addToDebt")
        self.gridLayout_8.addWidget(self.addToDebt, 0, 6, 1, 1)
        self.sell = QtWidgets.QPushButton(self.frame)
        self.sell.setMinimumSize(QtCore.QSize(50, 50))
        self.sell.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sell.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sell.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/add-to-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sell.setIcon(icon12)
        self.sell.setIconSize(QtCore.QSize(32, 32))
        self.sell.setObjectName("sell")
        self.gridLayout_8.addWidget(self.sell, 0, 5, 1, 1)
        self.restore = QtWidgets.QPushButton(self.frame)
        self.restore.setMinimumSize(QtCore.QSize(50, 50))
        self.restore.setMaximumSize(QtCore.QSize(16777215, 50))
        self.restore.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.restore.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"font: 15pt \"Amiri Quran\";\n"
"\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"border-bottom-width:2px;\n"
"border-top-color:white;\n"
"border-left-color:white;\n"
"border-right-color:white;\n"
"border-bottom-color:rgb(158, 158, 158)\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/newPrefix/backup-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore.setIcon(icon13)
        self.restore.setIconSize(QtCore.QSize(32, 32))
        self.restore.setObjectName("restore")
        self.gridLayout_8.addWidget(self.restore, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.h_table = QtWidgets.QTableWidget(self.page)
        self.h_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.h_table.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.h_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.h_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h_table.setObjectName("h_table")
        self.h_table.setColumnCount(4)
        self.h_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.h_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.h_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.h_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.h_table.setHorizontalHeaderItem(3, item)
        self.h_table.horizontalHeader().setDefaultSectionSize(200)
        self.h_table.horizontalHeader().setHighlightSections(True)
        self.h_table.horizontalHeader().setMinimumSectionSize(33)
        self.h_table.horizontalHeader().setSortIndicatorShown(True)
        self.h_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.h_table, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem27)
        self.h_bell_num = QtWidgets.QLabel(self.page)
        self.h_bell_num.setMinimumSize(QtCore.QSize(200, 50))
        self.h_bell_num.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.h_bell_num.setObjectName("h_bell_num")
        self.horizontalLayout_4.addWidget(self.h_bell_num)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setMinimumSize(QtCore.QSize(100, 50))
        self.label_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_2.setStyleSheet("font: 75 14pt \"Amiri\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.h_lcd = QtWidgets.QLCDNumber(self.page)
        self.h_lcd.setMinimumSize(QtCore.QSize(500, 50))
        self.h_lcd.setStyleSheet("background-color:black;\n"
"color:rgb(0, 255, 0)")
        self.h_lcd.setSmallDecimalPoint(True)
        self.h_lcd.setDigitCount(9)
        self.h_lcd.setMode(QtWidgets.QLCDNumber.Dec)
        self.h_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.h_lcd.setProperty("value", 0.0)
        self.h_lcd.setProperty("intValue", 0)
        self.h_lcd.setObjectName("h_lcd")
        self.horizontalLayout_4.addWidget(self.h_lcd)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.h_table.raise_()
        self.frame.raise_()
        self.line.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.d_tableContent_2 = QtWidgets.QTableWidget(self.page_10)
        self.d_tableContent_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.d_tableContent_2.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.d_tableContent_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.d_tableContent_2.setObjectName("d_tableContent_2")
        self.d_tableContent_2.setColumnCount(4)
        self.d_tableContent_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.d_tableContent_2.setHorizontalHeaderItem(3, item)
        self.d_tableContent_2.horizontalHeader().setDefaultSectionSize(200)
        self.d_tableContent_2.horizontalHeader().setSortIndicatorShown(True)
        self.d_tableContent_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_16.addWidget(self.d_tableContent_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_10)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sideBar = QtWidgets.QFrame(self.centralwidget)
        self.sideBar.setMinimumSize(QtCore.QSize(200, 0))
        self.sideBar.setStyleSheet("background-color:rgb(190, 190, 190);\n"
"")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sideBar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.STOCK = QtWidgets.QPushButton(self.sideBar)
        self.STOCK.setMinimumSize(QtCore.QSize(0, 50))
        self.STOCK.setMaximumSize(QtCore.QSize(16777215, 50))
        self.STOCK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.STOCK.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/newPrefix/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.STOCK.setIcon(icon14)
        self.STOCK.setIconSize(QtCore.QSize(32, 32))
        self.STOCK.setObjectName("STOCK")
        self.gridLayout_2.addWidget(self.STOCK, 2, 0, 1, 1)
        self.SETTINGS = QtWidgets.QPushButton(self.sideBar)
        self.SETTINGS.setMinimumSize(QtCore.QSize(0, 50))
        self.SETTINGS.setMaximumSize(QtCore.QSize(16777215, 50))
        self.SETTINGS.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SETTINGS.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/newPrefix/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SETTINGS.setIcon(icon15)
        self.SETTINGS.setIconSize(QtCore.QSize(32, 32))
        self.SETTINGS.setObjectName("SETTINGS")
        self.gridLayout_2.addWidget(self.SETTINGS, 5, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.sideBar)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.expired_date = QtWidgets.QPushButton(self.frame_2)
        self.expired_date.setGeometry(QtCore.QRect(0, 10, 171, 41))
        self.expired_date.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.expired_date.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/newPrefix/expired.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expired_date.setIcon(icon16)
        self.expired_date.setIconSize(QtCore.QSize(32, 32))
        self.expired_date.setObjectName("expired_date")
        self.ex_number = QtWidgets.QLabel(self.frame_2)
        self.ex_number.setGeometry(QtCore.QRect(0, 10, 31, 16))
        self.ex_number.setStyleSheet("background:rgb(255, 0, 0);\n"
"color:white;\n"
"font: 75 11pt \"Arial\";\n"
"border-radius:8px;\n"
"\n"
"")
        self.ex_number.setObjectName("ex_number")
        self.gridLayout_2.addWidget(self.frame_2, 7, 0, 1, 1)
        self.HOME = QtWidgets.QPushButton(self.sideBar)
        self.HOME.setMinimumSize(QtCore.QSize(0, 50))
        self.HOME.setMaximumSize(QtCore.QSize(16777215, 50))
        self.HOME.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.HOME.setStyleSheet("QPushButton{\n"
"  background-color:transparent;\n"
"border-style: outset;\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/newPrefix/house.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HOME.setIcon(icon17)
        self.HOME.setIconSize(QtCore.QSize(32, 32))
        self.HOME.setObjectName("HOME")
        self.gridLayout_2.addWidget(self.HOME, 1, 0, 1, 1)
        self.EXIT = QtWidgets.QPushButton(self.sideBar)
        self.EXIT.setMinimumSize(QtCore.QSize(0, 50))
        self.EXIT.setMaximumSize(QtCore.QSize(16777215, 50))
        self.EXIT.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.EXIT.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/newPrefix/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EXIT.setIcon(icon18)
        self.EXIT.setIconSize(QtCore.QSize(32, 32))
        self.EXIT.setObjectName("EXIT")
        self.gridLayout_2.addWidget(self.EXIT, 9, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem28, 10, 0, 1, 1)
        self.SELLS = QtWidgets.QPushButton(self.sideBar)
        self.SELLS.setMinimumSize(QtCore.QSize(0, 50))
        self.SELLS.setMaximumSize(QtCore.QSize(16777215, 50))
        self.SELLS.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SELLS.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/newPrefix/cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SELLS.setIcon(icon19)
        self.SELLS.setIconSize(QtCore.QSize(32, 32))
        self.SELLS.setObjectName("SELLS")
        self.gridLayout_2.addWidget(self.SELLS, 3, 0, 1, 1)
        self.DEBT = QtWidgets.QPushButton(self.sideBar)
        self.DEBT.setMinimumSize(QtCore.QSize(15, 50))
        self.DEBT.setMaximumSize(QtCore.QSize(16777215, 50))
        self.DEBT.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.DEBT.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        self.DEBT.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DEBT.setIcon(icon2)
        self.DEBT.setIconSize(QtCore.QSize(32, 32))
        self.DEBT.setObjectName("DEBT")
        self.gridLayout_2.addWidget(self.DEBT, 4, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem29, 0, 0, 1, 1)
        self.restore_page = QtWidgets.QPushButton(self.sideBar)
        self.restore_page.setMaximumSize(QtCore.QSize(16777215, 50))
        self.restore_page.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.restore_page.setStyleSheet("QPushButton{\n"
"\n"
"border-style: outset;\n"
"\n"
"    font: 15pt \"Amiri Quran\";\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(213, 213, 213)\n"
"}")
        self.restore_page.setIcon(icon13)
        self.restore_page.setIconSize(QtCore.QSize(32, 32))
        self.restore_page.setObjectName("restore_page")
        self.gridLayout_2.addWidget(self.restore_page, 6, 0, 1, 1)
        self.verticalLayout.addWidget(self.sideBar)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Machrou3"))
        item = self.d_tableContent.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم الزبون"))
        item = self.d_tableContent.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "اسم الزبون"))
        item = self.d_tableContent.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "اجمالي الديون"))
        item = self.d_tableContent.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "التاريخ"))
        self.d_search_input.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.d_showBook.setText(_translate("MainWindow", "اظهار دفتر الديون"))
        self.d_deleteUser.setText(_translate("MainWindow", "حذف زبون"))
        self.d_addUser.setText(_translate("MainWindow", "اضافة زبون"))
        self.label_3.setText(_translate("MainWindow", "اجمالي الديون"))
        self.label.setText(_translate("MainWindow", "عدد المنتجات"))
        item = self.s_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم المنتج"))
        item = self.s_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "اسم المنتج"))
        item = self.s_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "الكمية"))
        item = self.s_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "سعر الشراء"))
        item = self.s_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "سعر البيع"))
        item = self.s_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "نهاية الصلاحية"))
        item = self.s_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "التاريخ"))
        self.s_input.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.s_update.setText(_translate("MainWindow", "تعديل"))
        self.s_delete.setText(_translate("MainWindow", "حذف منتج"))
        self.s_add.setText(_translate("MainWindow", "اضافة منتج"))
        item = self.u_page_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم الفاتورة"))
        item = self.u_page_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "المبلغ"))
        item = self.u_page_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "التاريخ"))
        self.pay.setText(_translate("MainWindow", "دفع"))
        self.updateInfo.setText(_translate("MainWindow", "تعديل"))
        self.u_page_delete.setText(_translate("MainWindow", "حذف"))
        self.u_page_show.setText(_translate("MainWindow", "اظهار الفاتورة"))
        self.label_6.setText(_translate("MainWindow", "5"))
        self.label_4.setText(_translate("MainWindow", "رقم:"))
        self.u_page_phone.setText(_translate("MainWindow", "07716587"))
        self.label_7.setText(_translate("MainWindow", "رقم الهاتف:"))
        self.u_page_name.setText(_translate("MainWindow", "حمزة قطاف"))
        self.label_5.setText(_translate("MainWindow", "الاسم : "))
        item = self.expired_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم المنتج"))
        item = self.expired_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "اسم المنتج"))
        item = self.expired_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "الكمية"))
        item = self.expired_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "التاريخ"))
        self.delete_user.setText(_translate("MainWindow", "حذف "))
        self.update_user.setText(_translate("MainWindow", "تعديل"))
        self.add_user.setText(_translate("MainWindow", "اضافة"))
        item = self.table_user.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم العميل"))
        item = self.table_user.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "اسم العميل"))
        item = self.table_user.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "رقم الهاتف"))
        item = self.table_user.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "الدور"))
        item = self.bellTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم الفاتورة"))
        item = self.bellTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "البائع"))
        item = self.bellTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "التاريخ"))
        self.bell_input.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.deleteBell.setText(_translate("MainWindow", "حذف "))
        self.showBell.setText(_translate("MainWindow", "اظهار الفاتورة"))
        self.user_settings.setText(_translate("MainWindow", "اعدادت العملاء"))
        self.gen_barcode.setText(_translate("MainWindow", "انشاء بار كود"))
        self.exDB.setText(_translate("MainWindow", "استخراج قاعدة البيانات"))
        self.download.setText(_translate("MainWindow", "استيراد منتجات "))
        self.analytic.setText(_translate("MainWindow", "الاحصائيات"))
        self.email.setPlaceholderText(_translate("MainWindow", "Username"))
        self.signin.setText(_translate("MainWindow", "دخول"))
        self.label_8.setText(_translate("MainWindow", "تسجيل الدخول"))
        self.password.setPlaceholderText(_translate("MainWindow", "password"))
        self.choose_file.setText(_translate("MainWindow", "اختر ملف"))
        item = self.excel_tale.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم المنتج"))
        item = self.excel_tale.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "اسم المنتج"))
        item = self.excel_tale.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "الكمية"))
        item = self.excel_tale.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "سعر الشراء"))
        item = self.excel_tale.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "سعر البيع"))
        item = self.excel_tale.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "نهاية الصلاحية"))
        item = self.excel_tale.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "التاريخ"))
        self.saveTodb.setText(_translate("MainWindow", "حفظ"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "اجمالي المبيعات"))
        self.today_earns.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "ارباح اليوم"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "اجمالي الارباح"))
        item = self.productsName.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "اسم المنتج"))
        self.h_add.setText(_translate("MainWindow", "اضف"))
        self.printBell.setText(_translate("MainWindow", "طباعة الفاتورة"))
        self.h_input.setPlaceholderText(_translate("MainWindow", "0"))
        self.h_delete.setText(_translate("MainWindow", "حذف"))
        self.addToDebt.setText(_translate("MainWindow", "اضف للديون"))
        self.sell.setText(_translate("MainWindow", "بيع"))
        self.restore.setText(_translate("MainWindow", "ارجاع"))
        item = self.h_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم المنتج"))
        item = self.h_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "اسم المنتج"))
        item = self.h_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "الكمية"))
        item = self.h_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "السعر"))
        self.h_bell_num.setText(_translate("MainWindow", "0000000"))
        self.label_2.setText(_translate("MainWindow", "رقم الفاتورة"))
        item = self.d_tableContent_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "رقم المنتج"))
        item = self.d_tableContent_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "اسم المنتج"))
        item = self.d_tableContent_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "البائع"))
        item = self.d_tableContent_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "التاريخ"))
        self.STOCK.setText(_translate("MainWindow", "            المخزن"))
        self.SETTINGS.setText(_translate("MainWindow", "        الاعدادات"))
        self.expired_date.setText(_translate("MainWindow", "      منتجات منتهية "))
        self.ex_number.setText(_translate("MainWindow", "+99"))
        self.HOME.setText(_translate("MainWindow", "الصفحة الرئيسية"))
        self.EXIT.setText(_translate("MainWindow", "              خروج"))
        self.SELLS.setText(_translate("MainWindow", "           المبيعات"))
        self.DEBT.setText(_translate("MainWindow", "       دفتر الديون"))
        self.restore_page.setText(_translate("MainWindow", "      السلع المردة"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
