# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printdoc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, html):
        self.html = html 


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 620)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 901, 571))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 899, 569))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pdfDoc = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.pdfDoc.setReadOnly(True)
        self.pdfDoc.setObjectName("pdfDoc")
        self.gridLayout_2.addWidget(self.pdfDoc, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.print = QtWidgets.QPushButton(Form)
        self.print.setGeometry(QtCore.QRect(9, 585, 901, 26))
        self.print.setObjectName("print")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pdfDoc.setHtml(_translate("Form", self.html))
        self.print.setText(_translate("Form", "طباعة"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
