# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enterQuantity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 204)
        Dialog.setMaximumSize(QtCore.QSize(400, 204))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:white\n"
"")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 160, 161, 32))
        self.buttonBox.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 351, 51))
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add quantity"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Quantity"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
