# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'restore.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 312)
        Dialog.setMaximumSize(QtCore.QSize(400, 312))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:White")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 161, 32))
        self.buttonBox.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.proName_r = QtWidgets.QLineEdit(Dialog)
        self.proName_r.setGeometry(QtCore.QRect(32, 50, 351, 41))
        self.proName_r.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.proName_r.setObjectName("proName_r")
        self.dbt_r = QtWidgets.QCheckBox(Dialog)
        self.dbt_r.setGeometry(QtCore.QRect(190, 150, 191, 41))
        self.dbt_r.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dbt_r.setStyleSheet("font: 75 12pt \"Amiri\";")
        self.dbt_r.setObjectName("dbt_r")
        self.dtUser_r = QtWidgets.QLineEdit(Dialog)
        self.dtUser_r.setGeometry(QtCore.QRect(30, 200, 351, 41))
        self.dtUser_r.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.dtUser_r.setObjectName("dtUser_r")
        self.Quantity_ = QtWidgets.QLineEdit(Dialog)
        self.Quantity_.setGeometry(QtCore.QRect(30, 100, 351, 41))
        self.Quantity_.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.Quantity_.setObjectName("Quantity_")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Restore"))
        self.proName_r.setPlaceholderText(_translate("Dialog", "ادخل البار كود / اسم المنج او السعر"))
        self.dbt_r.setText(_translate("Dialog", "حذف من الديون"))
        self.dtUser_r.setPlaceholderText(_translate("Dialog", "اسم الزبون"))
        self.Quantity_.setPlaceholderText(_translate("Dialog", "ادخل الكمية"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
