# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(987, 597)
        Dialog.setMaximumSize(QtCore.QSize(987, 597))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:rgb(51, 143, 255)")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.file_link = QtWidgets.QLabel(Dialog)
        self.file_link.setMinimumSize(QtCore.QSize(500, 50))
        self.file_link.setMaximumSize(QtCore.QSize(16777215, 50))
        self.file_link.setStyleSheet("background:white")
        self.file_link.setText("")
        self.file_link.setObjectName("file_link")
        self.horizontalLayout.addWidget(self.file_link)
        self.choose_file = QtWidgets.QPushButton(Dialog)
        self.choose_file.setMinimumSize(QtCore.QSize(0, 50))
        self.choose_file.setMaximumSize(QtCore.QSize(16777215, 50))
        self.choose_file.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.choose_file.setObjectName("choose_file")
        self.horizontalLayout.addWidget(self.choose_file)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 400))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame.setStyleSheet("background:white;\n"
"border-radius:25px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.excel_tale = QtWidgets.QTableWidget(self.frame)
        self.excel_tale.setGeometry(QtCore.QRect(10, 20, 951, 361))
        self.excel_tale.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.excel_tale.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #616161, stop: 0.5 #505050,\n"
"                                      stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"   \n"
"}")
        self.excel_tale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.excel_tale.setWordWrap(True)
        self.excel_tale.setCornerButtonEnabled(False)
        self.excel_tale.setObjectName("excel_tale")
        self.excel_tale.setColumnCount(7)
        self.excel_tale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.excel_tale.setHorizontalHeaderItem(6, item)
        self.excel_tale.horizontalHeader().setDefaultSectionSize(200)
        self.excel_tale.horizontalHeader().setSortIndicatorShown(True)
        self.excel_tale.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonBox.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(738, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Products"))
        self.choose_file.setText(_translate("Dialog", "اختر ملف"))
        item = self.excel_tale.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "رقم المنتج"))
        item = self.excel_tale.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "اسم المنتج"))
        item = self.excel_tale.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "الكمية"))
        item = self.excel_tale.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "سعر الشراء"))
        item = self.excel_tale.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "سعر البيع"))
        item = self.excel_tale.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "نهاية الصلاحية"))
        item = self.excel_tale.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "التاريخ"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
