# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(712, 431)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:white")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.auto_generate = QtWidgets.QCheckBox(Dialog)
        self.auto_generate.setMinimumSize(QtCore.QSize(50, 0))
        self.auto_generate.setMaximumSize(QtCore.QSize(150, 16777215))
        self.auto_generate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.auto_generate.setObjectName("auto_generate")
        self.horizontalLayout.addWidget(self.auto_generate)
        self.barcodeInput = QtWidgets.QLineEdit(Dialog)
        self.barcodeInput.setMinimumSize(QtCore.QSize(400, 50))
        self.barcodeInput.setMaximumSize(QtCore.QSize(400, 16777215))
        self.barcodeInput.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.barcodeInput.setReadOnly(False)
        self.barcodeInput.setObjectName("barcodeInput")
        self.horizontalLayout.addWidget(self.barcodeInput)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(100, 50))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setStyleSheet("font: 75 12pt \"Amiri\";\n"
"margin-right: 35px")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setMinimumSize(QtCore.QSize(500, 50))
        self.spinBox_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.spinBox_2.setStyleSheet("background:white;\n"
"border-style: outset;\n"
"border-color:rgb(221, 221, 221);\n"
"border-width:0.5px;\n"
"border-right-color:white;\n"
"border-left-color:white;\n"
"border-top-color:white;\n"
"\n"
"border-top-left-radius:15px")
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(55)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(150, 50))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setStyleSheet("font: 75 12pt \"Amiri\";\n"
"margin-right: 35px")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.barcode_container = QtWidgets.QLabel(Dialog)
        self.barcode_container.setMinimumSize(QtCore.QSize(0, 250))
        self.barcode_container.setText("")
        self.barcode_container.setObjectName("barcode_container")
        self.gridLayout.addWidget(self.barcode_container, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonBox.setStyleSheet("border-style: outset;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background:orange;\n"
"height: 100px;\n"
"width:100px;\n"
"border-radius: 15px;\n"
"font: 75 11pt \"Amiri\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Barcode"))
        self.auto_generate.setText(_translate("Dialog", "auto generate"))
        self.barcodeInput.setPlaceholderText(_translate("Dialog", "ادخل الكود بار"))
        self.label.setText(_translate("Dialog", "كود بار"))
        self.label_2.setText(_translate("Dialog", "عدد النسخ"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
